### ISSUE TITLE
need to be updated

### ISSUE THREAD

**Issue by mofada** [MrYsLab/pseudo-microbit#2]
Hello, is the project still under maintenance? Dependency needs to be updated.

**Comment by MrYsLab** [comment]
I don't understand what you mean by dependency? Could you please describe exactly what you mean?

**Comment by mofada** [comment]
I can't find some modules, such as utime/ustruct

![image](https://user-images.githubusercontent.com/22286246/97936152-a89bc900-1db5-11eb-9974-9bbba288a01b.png)

![image](https://user-images.githubusercontent.com/22286246/97936235-da149480-1db5-11eb-8d39-635bfdda4edc.png)

**Comment by MrYsLab** [comment]
There has been an [outstanding issue](https://github.com/bbcmicrobit/micropython/issues/655) against bbcmicrobit since July of 2019 about updating its documentation. When that is resolved and when a new release of micropython becomes available for the micro:bit v2, I will consider updating this package.

In the meantime, you may implement support for usleep by [looking at the code](https://github.com/MrYsLab/pseudo-microbit/blob/f50d6210b9f79d5d96045d4e0befad9b500ca31d/microbit/__init__.py#L49) that implements sleep.  You can do something similar for ustruct as well.

**Comment by mofada** [comment]
I have a hcsr04 ultrasound module that I need to use, and I need to use this `from machine import time_pulse_us`, the code prompt will not find this module, the actual burning and running is no problem, but the code looks red and a bit weird

**Comment by MrYsLab** [comment]
Version 1.12 corrects this issue, so I am closing it. Please let me know if you have any questions or comments.

Please note that the User Guide has changed significantly since the assumption is that the PyCharm project created is within a virtual environment. 

I also replaced the code minimizer with python-minimizer.
