### ISSUE TITLE
529 Error Code when Flashing Code to micro:bit V2

### ISSUE THREAD

**Issue by vkb008** [MrYsLab/pseudo-microbit#6]
When flashing code thru PyCharm/uflash external tool, I am getting 529 error code. I verified flashing firmware thru the make code editor website and I am able to flash programs without issue. Any suggestions?

**Comment by vkb008** [comment]
To add more detail to this, after running `uflash` when I open the microbit drive on my Pi 4, there is a `fail.txt` inside that says this:

![failTextFile](https://user-images.githubusercontent.com/4166458/101370184-095b6d00-385e-11eb-84bf-ab3ed012551b.png)

I have also reached out to micro:bit support as well, but if anyone using this pseudo-microbit implementation has any suggestions, it would be great to hear.

**Comment by MrYsLab** [comment]
There is a [page ](https://tech.microbit.org/software/hex-format/)that describes that the hex file format has changed. The micro:bit folks point to a[ tool ](https://tech.microbit.org/software/universal-hex-creator/)on that page that will create hex files with the latest format. This does not solve your immediate problem, since you are looking for an integrated solution. However, the author of uflash is aware of this issue and it is documented [here](https://github.com/ntoll/uflash/issues/67). Hopefully, he will get to the fix soon. But since this issue has been outstanding for about a month, I am not sure when it will be resolved.

I will be facing this issue in the near future since I am intending on creating a version of Telemetrix for the micro:bit V2.
I cannot give an estimate as to when I will be getting to this, but it should be within the next couple of weeks. I would prefer that uflash fix the issue, but if not, I will look into creating my own version of uflash.

I have also found this [repo](https://github.com/Krakenus/microbit-micropython-bakefile), but do not know if it is using the latest hex file format or not.

I am closing this issue, but again, you can leave additional comments or questions.

**Comment by vkb008** [comment]
Thanks for the heads up. 

Until this integrated uflash is up and running with V2, I will just upload my .py file, that I want to flash, to the [make code python editor](https://python.microbit.org/v/2). It looks like I am able to successfully flash by doing this.

**Comment by MrYsLab** [comment]
Great! The micro:bit folks should have had a soultion in hand but did not. I am not sure what the advantage (if any) of changing the hex file format was, but one thing we know for sure - it broke their "standard" set of tools. ;-).

I think the mu editor may also be suffering from the same problem. It appears the changes were made in the middle of the night, while no one on the micropython side was notified. What a mess!

**Comment by vkb008** [comment]
Interesting. I guess because the micro:bit is a "fun at home tool", they can get away with issues like this. I'm sure most people using these products just use the make code editor online, so they won't notice any of this.

General question - I've seen on the [make code support site](https://support.microbit.org/support/solutions/articles/19000083637-using-the-micro-bit-wirelessly-) that **BLE is not supported in MicroPython**

Can I still use your pseudo-microbit implementation in PyCharm when writing BLE-related scripts and not run into issues? _I'm assuming yes because PyCharm itself is running on Python, not MicroPython._ Is this _statement_ correct?

**Comment by MrYsLab** [comment]
I don't know if the problem with micro:bit is a funding issue or not, but you are correct, it seems as though makecode is their main platform. My guess is that Microsoft strives to keep things up to date, whereas the micropython side of the house, being supported by private individuals just does not have the resources to address the issues in a timely fashion.

The reason that BLE was not supported in micropython was that the limited resources of the micro: bit version 1 could not handle the additional resource requirements to support the library. I don't think the micropython folks have published a BLE library for micro:bit as of yet.

Yes, you can still use pseudo-microbit with BLE, however, it does not know anything about BLE and therefore you are most likely to get "syntax" errors.
 
The Telemetrix version I am planning on implementing for the micro:bit will not be using micropython. I love Python, but micropython is very, very slow when compared with an equivalent compiled application. I do not know if I will be successful or not, but my plan is to use the [Arduino-Core](https://github.com/sandeepmistry/arduino-nRF5) for the processor. Using this scheme, the micro:bit will be controlled from a remote Python computer connected via serial or BLE link. Of course, this means that the application will not run stand-alone. 

I have built Telemetrix servers for the Arduino AVR processors, STM32 processors, the ESP-8266 and am currently working on the ESP32 all using the Arduino-Core.

Unfortunately, the JetBrains IDEs do not support embedded processors very well, so I am using VSCode in conjunction with PlatformIO. It has its own warts, but I am able to include additional sensor/actuator libraries and upload the image all within VSCode. The only thing that it can't do is maintain the wacky directory structure and file naming (.ino) that Arduino uses. But the advantage is that my servers can be installed using the Arduino library manager that makes life a lot simpler for both me and my users, once I move things over to the accepted Arduino directory structure and naming convention.

VSCode with the Arduino-Core can be used to create compiled standalone applications, with the only downside is that you have to write things in C/C++. I programmed in C/C++ for a very long time, and still find it painful to do so. Only if micropython generated an optimized compiled image ;-).
