### ISSUE TITLE
Cannot import name 'Image' from partially initialized module 'microbit'

### ISSUE THREAD

**Issue by OevreFlataeker** [MrYsLab/pseudo-microbit#7]
I'm getting this error whenever I try to "from microbit import *". Tried in Windows with Python 3.10 and Linux with Python 3.8. Tried installing in a venv as well as in system scope. Same result. 

```
(mbit)  python3
Python 3.8.10 (default, Sep 28 2021, 16:10:42)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from microbit import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/mbit/lib/python3.8/site-packages/microbit/__init__.py", line 31, in <module>
    from . import (display as display, uart as uart, spi as spi, i2c as i2c,
  File "/tmp/mbit/lib/python3.8/site-packages/microbit/display.py", line 12, in <module>
    from . import Image
ImportError: cannot import name 'Image' from partially initialized module 'microbit' (most likely due to a circular import) (/tmp/mbit/lib/python3.8/site-packages/microbit/__init__.py)
```

Installed the package using pip install pseudo-microbit without issue.

**Comment by MrYsLab** [comment]
Hi @OevreFlataeker
The purpose of pseudo-microbit is to allow one to edit a micro:bit MicroPython file within PyCharm. It was not meant as a run-time package. The file created using pseudo-microbit and PyCharm, must be uploaded to an actual micro:bit device to run.

The [tutorial](https://mryslab.github.io/pseudo-microbit/) explains how to install and use the package. If you are using a micro:bit v2 module, the uflash utility described in the tutorial cannot be used. This issue is documented [here.](https://github.com/ntoll/uflash/issues/67)

If you have any questions, I would be happy to answer them. I am closing this issue, but you may post here, and I will see them.

Thanks.
